import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';

/// Loads and holds the active flow graph mapping in memory.
///
/// ## Loading strategies (V3 - CodeGen):
/// `lib/ats_generated.dart` is automatically created by `ats sync`
/// and natively imported in `main.dart`, achieving true O(1) memory mapping.
class FlowRegistry {
  final Map<String, List<String>> _activeMethodsMap;
  final List<String> _activeFlows;

  FlowRegistry._(this._activeMethodsMap, this._activeFlows);

  /// Load the flow mapping natively.
  factory FlowRegistry.fromNative(
      Map<String, List<String>> staticMap, List<String> activeFlows) {
    // We strictly use the provided collections since they are generated natively.
    final registry = FlowRegistry._(staticMap, activeFlows);
    debugPrint('[ATS] Registry initialized via CodeGen.');
    _logActive(registry);
    return registry;
  }

  /// Build a registry directly from test stubs.
  factory FlowRegistry.fromMock(String mapString, String flowsString) {
    final registry = FlowRegistry._({}, []);
    registry._parse(mapString, flowsString);
    return registry;
  }

  /// Load the flow mapping. O(1) inverted index generation.
  static Future<FlowRegistry> load({String? customPath}) async {
    final registry = FlowRegistry._({}, []);

    // ── Strategy 1: dart-define (works on ALL platforms, including mobile) ──
    const inlineMap =
        String.fromEnvironment('ATS_METHOD_MAP', defaultValue: '');
    const inlineFlows =
        String.fromEnvironment('ATS_ACTIVE_FLOWS', defaultValue: '');

    if (inlineMap.isNotEmpty || inlineFlows.isNotEmpty) {
      registry._parse(inlineMap, inlineFlows);
      debugPrint('[ATS] Loaded from --dart-define.');
      _logActive(registry);
      return registry;
    }

    // ── Strategy 2: dart:io (desktop — reads dart_defines.json generated by CLI)
    if (!kIsWeb) {
      final path = customPath ?? '.ats/dart_defines.json';
      final file = File(path);
      if (file.existsSync()) {
        try {
          final json =
              jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
          final mapString = json['ATS_METHOD_MAP'] as String? ?? '';
          final flowsString = json['ATS_ACTIVE_FLOWS'] as String? ?? '';
          registry._parse(mapString, flowsString);
          debugPrint('[ATS] Loaded from fallback file: $path');
          _logActive(registry);
          return registry;
        } catch (e) {
          debugPrint('[ATS] ⚠️  Failed to parse $path: $e');
        }
      }
    }

    // ── Not found ────────────────────────────────────────────────────────────
    debugPrint(
      '[ATS] ⚠️  ATS mapping config not found.\n'
      '     Make sure to launch via VSCode F5 (with preLaunchTask "ats_sync")\n'
      '     Or run using `ats run`.',
    );
    return registry;
  }

  void _parse(String mapString, String flowsString) {
    if (mapString.isNotEmpty) {
      final decoded = jsonDecode(mapString) as Map<String, dynamic>;
      for (final entry in decoded.entries) {
        _activeMethodsMap[entry.key] = (entry.value as List).cast<String>();
      }
    }
    if (flowsString.isNotEmpty) {
      _activeFlows.addAll((jsonDecode(flowsString) as List).cast<String>());
    }
  }

  static void _logActive(FlowRegistry r) {
    if (r._activeFlows.isEmpty) {
      debugPrint('[ATS] Registry loaded. No flows active.');
    } else {
      debugPrint('[ATS] Active flows: ${r._activeFlows}');
    }
  }

  /// Returns active flows designated for this method name [className].[methodName].
  /// Returns empty list if method is not traced by any active flow (O(1)).
  List<String> getFlowsForMethod(String className, String methodName) {
    return _activeMethodsMap['$className.$methodName'] ?? [];
  }

  /// Returns true if [flowName] is currently active.
  bool isActive(String flowName) => _activeFlows.contains(flowName);

  /// Returns a debug-friendly summary.
  Map<String, dynamic> toDebugMap() => {
        'mapped_methods': _activeMethodsMap.length,
        'active_flows': _activeFlows,
        'mapping_keys': _activeMethodsMap.keys.toList(),
      };
}
